name: ${artifactId}
version: ${version}
description: Provides graphical menu systems using inventories
main: co.neweden.menugui.Main
author: AaronMcH
website: https://neweden.co/
commands:
   menugui:
      description: Commands to manage MenuGUI
      permission: menugui.manage