name: MenuGUI
description: Provides graphical menu systems using inventories
main: co.neweden.menugui.Main
version: 1.0
author: AaronMcH
website: https://neweden.co/
commands:
   menugui:
      description: Commands to manage MenuGUI
      permission: menugui.manage